### ISSUE TITLE
Finalize recommendations for TAITs

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/types-team#40]
### Summary
* Review (or perhaps create) finalized recommendations for TAIT stabilization (and esp. considering RPIT hacks)

### Rationale
Finalizing TAITs is one of our goals

**Comment by nikomatsakis** [comment]
Scheduled for May 20

**Comment by jackh726** [comment]
We discussed this in a deep dive meeting: https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/2022-09-16.20TAIT.20stabilization.20finalizations

Doc: https://hackmd.io/FNLjLrevQcSKoIDAsf9ivQ#2022-09-16---Status-Update-T-types-Deep-Dive
