### ISSUE TITLE
Polonius status update

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/types-team#43]
### Summary

Update folks on status of polonius and proposed next steps

**Comment by nikomatsakis** [comment]
We had this meeting at .. some point. The result was this proto roadmap: https://hackmd.io/dbILOXy-SYWVu4ISehGKgg?view

**Comment by oli-obk** [comment]
https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/meeting.202022-07-01/near/288172885 may have been the meeting
