### ISSUE TITLE
use `ObligationCtxt` for canonical queries

### ISSUE THREAD

**Issue by lcnr** [rust-lang/types-team#50]
# Proposal

Canonical queries are currently implemented using an extension trait for `InferCtxt` and manually create a `FulfillmentContext`.

Considering that literally all uses of `enter_with_canonical` create a `FulfillmentContext` right away, moving all of this to `ObligationCtxt` seems like a sensible step to me.

# Mentors or Reviewers

*If you have a reviewer or mentor in mind for this work, mention then
here. You can put your own name here if you are planning to mentor the
work.*

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [x] A types team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Types team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/types/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by compiler-errors** [comment]
seconded, even if rustbot won't do anything yet

**Comment by compiler-errors** [comment]
I wonder if this works...

@rustbot second
