### ISSUE TITLE
Chalk integration plan

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/types-team#54]
### Summary

Interactive design session to form a plan for how we will go about integrating a chalk-like solver

### Rationale

We've been talking about doing a chalk-like solver for a while. Let's make a plan and do it. By now, my feeling at least is that we may want to reimplement from scratch, taking the lessons from chalk but modeled more on a-mir-formality. Discuss the implications.

**Comment by jackh726** [comment]
We discussed this is in a deep dive meeting: https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/2022-09-30.20chalk.20integration

Doc: https://hackmd.io/mAANGq4ZTCu_dBW9weqVew?edit
