### ISSUE TITLE
How polonius fits in

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/types-team#56]
### Summary
Discuss how polonius would fit into the overall compiler architecture, especially in light of plans around chalk/mir-formality

### Rationale
There are several people interested in pushing on polonius, so let's figure out how it fits into the existing system.

**Comment by lcnr** [comment]
had a meeting about polonius: https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/2023-05-22.20polonius.20roadmap
