### ISSUE TITLE
Tracking issue for polonius

### ISSUE THREAD

**Issue by jackh726** [rust-lang/types-team#74]

**Comment by lqd** [comment]
Current status:
- up-to-date roadmap [published](https://blog.rust-lang.org/inside-rust/2023/10/06/polonius-update.html)
- location-insensitive analysis landed in rustc
  * until a-mir-formality formalism, implementation anticipated fuzzing: has uncovered 2 issues, now fixed
  * crater run that this is equivalent to NLLs is in-progress
    - 1 full run complete, uncovered a difference on 10 crates, looks like same root cause
    - PR open to fix that, and new crater run on regressions is in queue
- various cleanups of borrowck, NLLs, and legacy polonius have landed
- onboarding Amanda, starting with higher-ranked task from the roadmap
- no new progress on borrowck/polonius in a-mir-formality just yet on our side, but there are plans in ralf's team
- moving on to location-sensitivity

**Comment by jackh726** [comment]
Closing in favor of #108
