### ISSUE TITLE
Add experimental support for implication predicates

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/types-team#80]
# Proposal

Implement implication predicates `[A1, A2, ..] => B` that have the the following behavior:

* When evaluating `[A1, A2, ..] => B`, add `A1, A2, ..` to the existing param-env and evaluate `B` under that new param-env.
* When evaluating whether some predicate `B` holds, and we have an implication predicate `[A1, A2, ..] => B` in the param-env, then that predicate may satisfy `B` if the nested obligations `A1, A2, ..` hold.

This proposal does not suggest adding surface syntax for these predicates yet, just adding them to the "middle" type layer.

Side-note: If anyone thinks this should be a compiler MCP, I'd be happy to move this over there. If this is better suited for a T-lang initiative, or needs a pre-RFC, then let me know.

# Mentors or Reviewers

I've got a branch that mostly implements support for this. I'd probably start over from scratch since I'd want to audit all the places I added `todo!()`s for these predicates though. I don't want to put up a PR for it unless the team is interested in supporting this in the trait system, though.

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A types team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Types team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/types/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by jackh726** [comment]
@rustbot second

As stated on zulip, I don't think this really needs an MCP, since it aligns with our "vision" of the future type system in a-mir-formality.

But, for process, seconding.

**Comment by jackh726** [comment]
Closing as accepted.
