### ISSUE TITLE
Add experimental support for `for<T>` binders in limited positions

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/types-team#81]
# Proposal

Modify the resolver and type system to support `for<T>` in **where clauses and associated item bounds** (not object types or return-position impl traits). 

### Why?
1. They should eventually also be useful for things like where clauses involving GATs (e.g. `where for<T> Self::Assoc<T>: Trait`).
1. This will allow us to test out `ty::Bound` and `ty::Placeholder` a bit more, even if currently they're pretty useless on their own (i.e. without implication predicates).
1. They should eventually work synergistically with implication predicates, if or when we add support for those (e.g. `where for<T: Debug> Self::Assoc<T>: Debug`).

Side-note: If anyone thinks this should be a compiler MCP, I'd be happy to move this over there. If this is better suited for a T-lang initiative, or needs a pre-RFC, then let me know.

# Mentors or Reviewers

I've got a branch that mostly implements support for this, but it needs *major* cleaning up. I'm willing to do that work, but I just don't want to invest too much time to clean it up unless there's reasonable interest in support for type binders from other team members.
https://github.com/rust-lang/rust/compare/master...compiler-errors:rust:non_lifetime_binders

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A types team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Types team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/types/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by jackh726** [comment]
@rustbot second

The actual PR for this will likely need lang okay, but from a types perspective, I think it's a good feature to experiment with.

**Comment by compiler-errors** [comment]
Cool, noted

**Comment by zyansheep** [comment]
Would this addition resolve https://github.com/rust-lang/rfcs/issues/1481 ?

**Comment by compiler-errors** [comment]
@zyansheep, yes

**Comment by lcnr** [comment]
closing as accepted

**Comment by BoxyUwU** [comment]
yes: rust-lang/rust#108185

fyi for any follow up comments please use the associated [zulip stream](https://rust-lang.zulipchat.com/#narrow/stream/326866-xxx/topic/Add.20experimental.20support.20for.20.60for.3CT.3E.60.20binders.E2.80.A6.20types-team.2381) of this MCP or open a thread in the [#t-types](https://rust-lang.zulipchat.com/#narrow/channel/144729-t-types) channel
