### ISSUE TITLE
Associated type bounds

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/types-team#88]
### Summary

Figure out a plan around stabilization (or removal) of assoc type bounds

- the current implementation
- issues of the current approach
- what's needed to make progress here

### Rationale

These are a key part of the story for associated return types (neé Return Type Notation, or RTN). They've been RFC'd and (sort of) implemented for a while. What does it take to feel comfortable stabilizing? Is there a clear MVP?

**Comment by BoxyUwU** [comment]
This deep dive will be taking place on 21/8/2023. It was scheduled [here](https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/2023-08-07.20planning.20meeting/near/382658032)

**Comment by BoxyUwU** [comment]
this [took place](https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/2023-08-21.20associated.20type.20bounds). It is unclear to me if there is still more to talk about or not as I was not super present at this meeting

**Comment by jackh726** [comment]
I'm working on splitting out a feature gate for associated type bounds in associated types. Other than that, I think we concluded in the meeting that we're comfortable moving forward with stabilization. Don't think we need another meeting.
