### ISSUE TITLE
Remove chalk support from Rust

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/types-team#93]
# Proposal

As far as I'm aware, the Chalk compiler is deprecated[^1]. My understanding is that T-types will continue maintaining it for rust-analyzer, but we have no plans to continue integrating it into rustc and it's a bit of a burden on the compiler due to the interning layer from chalk <=> rustc and the specific workarounds that live in the compiler to accomodate for the chalk solver.

[^1]: https://blog.rust-lang.org/2023/01/20/types-announcement.html#formalizing-the-rust-type-system

# Mentors or Reviewers

I can implement the removal. The code should be very easy to review since it's just a bunch of code going away. 

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A types team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Types team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/types/mcp.html

# Comments

Not sure if this should be a full-fledged FCP. If so, I can open one on the removal PR.

**Comment by lcnr** [comment]
closing as accepted https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/2023-07-03.20planning.20meeting/near/372030757
