### ISSUE TITLE
early v late bound design and implementation background

### ISSUE THREAD

**Issue by lcnr** [rust-lang/types-team#94]
### Summary

summarize the status quo of early and late bound lifetimes, things we have to keep in mind going forward, and relevant current implementation details.

### Rationale

We currently don't have a shared understanding of the status quo and where we want to go from here. We also don't have any good documentation of this. This meeting should both result in a useful document we can merge into the `rustc-dev-guide` and a foundation for future discussions, e.g. https://github.com/rust-lang/rust/pull/103448

**Comment by BoxyUwU** [comment]
Will also be good since the current rustc_dev_guide information on early/late bound lifetimes imo is lacking on information so it will be good to fill that out a bit with stuff from the deep dive doc

**Comment by BoxyUwU** [comment]
This was [scheduled](https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/2023-07-03.20planning.20meeting/near/372036675) for `10/07/2023`

**Comment by BoxyUwU** [comment]
This deep dive was had [here](https://rust-lang.zulipchat.com/#narrow/stream/326132-t-types.2Fmeetings/topic/2023-07-10.20late.20vs.20early.20bound)
