### ISSUE TITLE
Rename some `RegionKind` variants to be inline with `TyKind`/`ConstKind`

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/types-team#95]
# Proposal

I would like to rename:
`RegionKind::EarlyBound` to `RegionKind::EarlyParam`
`RegionKind::Free` to `RegionKind::LateParam`
`RegionKind::LateBound` to `RegionKind::Bound`

I find this to be far more consistent with `TyKind`/`ConstKind`. It's taken me a while for it to properly stick what all the 3 variants are on `RegionKind` since they're so differently named than `TyKind`, and also have an entire extra variant for representing lifetime parameters. I think the meaning of `RegionKind::Free` would have been a lot clearer with `RegionKind::LateParam`.

I also think it's kind of confusing that `RegionKind::EarlyBound` gets used for early bound generic paramaters but we do not use `RegionKind::LateBound` for late bound generic parameters. I think its unnecessarily confusing to draw a parallel between `ReLateBound`/`ReEarlyBound` and the concept of late/early bound generic parameters so directly when it does not actually apply. I am comfortable with drawing the parallel between `EarlyParam`/`LateParam` since it does not actually say Early/Late bound and in this case the parallel is actually present.

I would also like to avoid drawing a similarity between generic parameters and bound vars right now since we do not actually represent params with bound vars right now (and if we did we'd have to rename `RegionKind::LateBound` to `RegionKind::Bound` anyway).

Renaming `EarlyBound`/`Free` is it a bit of a wasted effort if we end up removing them in favor of placeholders and boundvars but this seems really simple to do wheras it's probably more complex to replace our param representation with bound vars as was briefly discussed in the t-types meeting on early/late bound parameters.

I do not work with regions very much since I don't touch borrowck much. I'd feel much more comfortable if someone who has spent a fair amount of time working with regions would approve this or say this is a coherent naming scheme for the regions.

# Mentors or Reviewers

I can review this or implement this or mentor this. I think really anybody on t-compiler-contributors or t-types is qualified to do any of those 3 things.

# Process

The main points of the [Major Change Process][MCP] are as follows:

* [x] File an issue describing the proposal.
* [ ] A types team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
    * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
    * Types team members can initiate a check-off via `@rfcbot fcp merge` on either the MCP or the PR.
* [ ] Once an MCP is seconded, the Final Comment Period begins. If no objections are raised after 10 days, the MCP is considered **approved**.

You can read [more about Major Change Proposals on forge][MCP].

[MCP]: https://forge.rust-lang.org/types/mcp.html

# Comments

**This issue is not meant to be used for technical discussion. There is a Zulip stream for that. Use this issue to leave procedural comments, such as volunteering to review, indicating that you second the proposal (or third, etc), or raising a concern that you would like to be addressed.**

**Comment by compiler-errors** [comment]
yeet

@rustbot second

**Comment by compiler-errors** [comment]
cc https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/naming.20bikeshedding/near/386440383

**Comment by WaffleLapkin** [comment]
Should this be considered accepted? the "second" comment was 2 months ago

**Comment by BoxyUwU** [comment]
Yeah it should lol
